version: '3'
services:
  postgresql-master:
    image: 'bitnami/postgresql:latest'
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_master_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_REPLICATION_MODE
      - POSTGRESQL_REPLICATION_USER
      - POSTGRESQL_REPLICATION_PASSWORD
      - POSTGRESQL_USERNAME
      - POSTGRESQL_PASSWORD
      - POSTGRESQL_DATABASE
  postgresql-slave:
    image: 'bitnami/postgresql:latest'
    ports:
      - '5433:5432'
    depends_on:
      - postgresql-master
    environment:
      - POSTGRESQL_REPLICATION_MODE
      - POSTGRESQL_REPLICATION_USER
      - POSTGRESQL_REPLICATION_PASSWORD
      - POSTGRESQL_MASTER_HOST
      - POSTGRESQL_USERNAME
      - POSTGRESQL_PASSWORD
      - POSTGRESQL_MASTER_PORT_NUMBER

  app:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: './'
    depends_on:
      - postgresql-slave
      - postgresql-master
    environment:
      - MASTER_DB_HOST
      - MASTER_DB_PORT
      - MASTER_DB_USER
      - MASTER_DB_PASSWORD
      - MASTER_DB_NAME
      - SLAVE_DB_HOST
      - SLAVE_DB_PORT
      - SLAVE_DB_USER
      - SLAVE_DB_PASSWORD
      - SLAVE_DB_NAME
volumes:
  postgresql_master_data:
