version: '3'
services:
  postgresql-master:
    image: 'bitnami/postgresql:latest'
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_master_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_USERNAME=mahan
      - POSTGRESQL_PASSWORD=secret
      - POSTGRESQL_DATABASE=appointments
  postgresql-slave:
    image: 'bitnami/postgresql:latest'
    ports:
      - '5433:5432'
    depends_on:
      - postgresql-master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=postgresql-master
      - POSTGRESQL_USERNAME=mahan
      - POSTGRESQL_PASSWORD=secret
      - POSTGRESQL_MASTER_PORT_NUMBER=5432

  app:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: './'
    depends_on:
      - postgresql-slave
      - postgresql-master
    environment:
      - MASTER_DB_HOST=postgresql-master
      - MASTER_DB_PORT=5432
      - MASTER_DB_USER=mahan
      - MASTER_DB_PASSWORD=secret
      - MASTER_DB_NAME=appointments
      - SLAVE_DB_HOST=postgresql-slave
      - SLAVE_DB_PORT=5432
      - SLAVE_DB_USER=mahan
      - SLAVE_DB_PASSWORD=secret
      - SLAVE_DB_NAME=appointments
volumes:
  postgresql_master_data:
